module ItamaePluginRecipeDaddy
  VERSION = "0.1.2"

  NGINX_VERSION = [
    NGINX_VERSION_MAJOR = '1',
    NGINX_VERSION_MINOR = '14',
    NGINX_VERSION_REVISION = '0'
  ].join('.')
  
  NGINX_RTMP_MODULE_VERSION = [
    NGINX_RTMP_MODULE_VERSION_MAJOR = '1',
    NGINX_RTMP_MODULE_VERSION_MINOR = '2',
    NGINX_RTMP_MODULE_VERSION_REVISION = '1'
  ].join('.')
  
  PASSENGER_VERSION = [
    PASSENGER_VERSION_MAJOR = '5',
    PASSENGER_VERSION_MINOR = '3',
    PASSENGER_VERSION_REVISION = '3'
  ].join('.')
end
