module ItamaePluginRecipeDaddy
  VERSION = '0.1.21'

  NGINX_VERSION = [
    NGINX_VERSION_MAJOR = '1',
    NGINX_VERSION_MINOR = '18',
    NGINX_VERSION_PATCH = '0'
  ].join('.')
  
  NGINX_RTMP_MODULE_VERSION = [
    NGINX_RTMP_MODULE_VERSION_MAJOR = '1',
    NGINX_RTMP_MODULE_VERSION_MINOR = '2',
    NGINX_RTMP_MODULE_VERSION_PATCH = '1'
  ].join('.')
  
  OPENCV_VERSION = [
    OPENCV_VERSION_MAJOR = '3',
    OPENCV_VERSION_MINOR = '3',
    OPENCV_VERSION_PATCH = '1'
  ].join('.')

  PYTHON_VERSION = [
    PYTHON_VERSION_MAJOR = '3',
    PYTHON_VERSION_MINOR = '6',
    PYTHON_VERSION_PATCH = '6'
  ].join('.')
  
  WKHTMLTOPDF_VERSION = [
    WKHTMLTOPDF_VERSION_MAJOR = '0',
    WKHTMLTOPDF_VERSION_MINOR = '12',
    WKHTMLTOPDF_VERSION_PATCH = '5-1'
  ].join('.')
end
